//! ffmpeg + GPU gated integration test for the full-timeline export spine
//! (`export::run_export`).
//!
//! Builds a single short video clip on a one-track timeline, runs the whole
//! orchestrator (plan → composite every frame → encode), and asserts the output
//! `.mp4` exists and `ffprobe` reads back the expected width/height/codec and a
//! matching frame count.
//!
//! Auto-skips when ffmpeg/ffprobe are missing OR when no GPU adapter is
//! available (CI/headless), so the default `cargo test` stays green offline.
//! Nothing is downloaded — the fixture media is generated by ffmpeg's lavfi.

use std::path::Path;
use std::process::Command;

use opentake_domain::{
    Clip, ClipType, MediaColorMetadata, MediaManifest, MediaManifestEntry, MediaSource, TextStyle,
    Timeline, Track,
};

/// True when both ffmpeg and ffprobe are on PATH.
fn ffmpeg_ready() -> bool {
    Command::new("ffmpeg")
        .arg("-version")
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false)
        && Command::new("ffprobe")
            .arg("-version")
            .output()
            .map(|o| o.status.success())
            .unwrap_or(false)
}

/// Generate an N-frame test video at `path`. Returns false (→ skip) on failure.
fn make_video(path: &Path, w: u32, h: u32, fps: u32, frames: u32) -> bool {
    let dur = frames as f64 / fps as f64;
    Command::new("ffmpeg")
        .args([
            "-v",
            "error",
            "-f",
            "lavfi",
            "-i",
            &format!("testsrc=duration={dur}:size={w}x{h}:rate={fps}"),
            "-c:v",
            "libx264",
            "-pix_fmt",
            "yuv420p",
            "-y",
        ])
        .arg(path)
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}

/// Generate a tagged Main10/PQ fixture. The x265 bitstream parameters are
/// intentional: container-only tags are not sufficient to exercise the HDR
/// decoder path used by the packaged application.
fn make_hdr_video(path: &Path, w: u32, h: u32, fps: u32, frames: u32) -> bool {
    Command::new("ffmpeg")
        .args([
            "-v",
            "error",
            "-f",
            "lavfi",
            "-i",
            &format!("testsrc2=size={w}x{h}:rate={fps}"),
            "-frames:v",
            &frames.to_string(),
            "-vf",
            "format=yuv420p10le",
            "-c:v",
            "libx265",
            "-preset",
            "ultrafast",
            "-x265-params",
            "log-level=error:hdr-opt=1:repeat-headers=1:colorprim=bt2020:transfer=smpte2084:colormatrix=bt2020nc",
            "-color_primaries",
            "bt2020",
            "-color_trc",
            "smpte2084",
            "-colorspace",
            "bt2020nc",
            "-y",
        ])
        .arg(path)
        .status()
        .map(|status| status.success())
        .unwrap_or(false)
}

fn decoded_rgb_range(path: &Path) -> Option<(u8, u8)> {
    let output = Command::new("ffmpeg")
        .args(["-v", "error", "-i"])
        .arg(path)
        .args(["-frames:v", "1", "-pix_fmt", "rgb24", "-f", "rawvideo", "-"])
        .output()
        .ok()?;
    if !output.status.success() || output.stdout.is_empty() {
        return None;
    }
    Some(
        output
            .stdout
            .into_iter()
            .fold((u8::MAX, u8::MIN), |(minimum, maximum), value| {
                (minimum.min(value), maximum.max(value))
            }),
    )
}

fn decoded_alpha_range(path: &Path) -> Option<(u8, u8)> {
    let output = Command::new("ffmpeg")
        .args(["-v", "error", "-i"])
        .arg(path)
        .args([
            "-vf",
            "alphaextract",
            "-frames:v",
            "1",
            "-pix_fmt",
            "gray",
            "-f",
            "rawvideo",
            "-",
        ])
        .output()
        .ok()?;
    if !output.status.success() || output.stdout.is_empty() {
        return None;
    }
    Some(
        output
            .stdout
            .into_iter()
            .fold((u8::MAX, u8::MIN), |(minimum, maximum), value| {
                (minimum.min(value), maximum.max(value))
            }),
    )
}

/// Generate an N-frame test video *with* a sine audio track. Returns false on
/// failure (→ skip).
fn make_video_with_audio(path: &Path, w: u32, h: u32, fps: u32, frames: u32) -> bool {
    let dur = frames as f64 / fps as f64;
    Command::new("ffmpeg")
        .args([
            "-v",
            "error",
            "-f",
            "lavfi",
            "-i",
            &format!("testsrc=duration={dur}:size={w}x{h}:rate={fps}"),
            "-f",
            "lavfi",
            "-i",
            &format!("sine=frequency=440:duration={dur}"),
            "-c:v",
            "libx264",
            "-pix_fmt",
            "yuv420p",
            "-c:a",
            "aac",
            "-shortest",
            "-y",
        ])
        .arg(path)
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}

/// True when the file has at least one audio stream (per ffprobe).
fn has_audio_stream(path: &Path) -> bool {
    let out = Command::new("ffprobe")
        .args([
            "-v",
            "error",
            "-select_streams",
            "a:0",
            "-show_entries",
            "stream=codec_type",
            "-of",
            "default=noprint_wrappers=1:nokey=1",
        ])
        .arg(path)
        .output();
    match out {
        Ok(o) => String::from_utf8_lossy(&o.stdout).trim() == "audio",
        Err(_) => false,
    }
}

/// ffprobe a single stream field as a trimmed string.
fn probe_field(path: &Path, entry: &str) -> Option<String> {
    let out = Command::new("ffprobe")
        .args([
            "-v",
            "error",
            "-select_streams",
            "v:0",
            "-show_entries",
            entry,
            "-of",
            "default=noprint_wrappers=1:nokey=1",
        ])
        .arg(path)
        .output()
        .ok()?;
    if !out.status.success() {
        return None;
    }
    Some(String::from_utf8_lossy(&out.stdout).trim().to_string())
}

/// Count decoded video frames via ffprobe.
fn probe_frame_count(path: &Path) -> Option<u64> {
    let out = Command::new("ffprobe")
        .args([
            "-v",
            "error",
            "-select_streams",
            "v:0",
            "-count_frames",
            "-show_entries",
            "stream=nb_read_frames",
            "-of",
            "default=noprint_wrappers=1:nokey=1",
        ])
        .arg(path)
        .output()
        .ok()?;
    String::from_utf8_lossy(&out.stdout).trim().parse().ok()
}

fn probe_duration(path: &Path) -> Option<f64> {
    let out = Command::new("ffprobe")
        .args([
            "-v",
            "error",
            "-show_entries",
            "format=duration",
            "-of",
            "default=noprint_wrappers=1:nokey=1",
        ])
        .arg(path)
        .output()
        .ok()?;
    String::from_utf8_lossy(&out.stdout).trim().parse().ok()
}

fn parse_rate(value: &str) -> Option<f64> {
    let (numerator, denominator) = value.split_once('/')?;
    let numerator: f64 = numerator.parse().ok()?;
    let denominator: f64 = denominator.parse().ok()?;
    (denominator > 0.0).then_some(numerator / denominator)
}

fn assert_summary_matches_real_probe(
    summary: &opentake_tauri_lib::export::ExportSummary,
    path: &Path,
) {
    let width: u32 = probe_field(path, "stream=width").unwrap().parse().unwrap();
    let height: u32 = probe_field(path, "stream=height").unwrap().parse().unwrap();
    let fps = parse_rate(&probe_field(path, "stream=avg_frame_rate").unwrap()).unwrap();
    let frame_count = probe_frame_count(path).unwrap();
    let duration = probe_duration(path).unwrap();
    let trusted_duration = f64::from(summary.frame_count) / f64::from(summary.fps);

    assert_eq!(summary.width, width);
    assert_eq!(summary.height, height);
    assert!((f64::from(summary.fps) - fps).abs() < 0.001);
    assert_eq!(u64::try_from(summary.frame_count).unwrap(), frame_count);
    assert!(
        (trusted_duration - duration).abs() <= 1.0 / f64::from(summary.fps) + 0.001,
        "producer duration {trusted_duration} must match ffprobe duration {duration}"
    );
    assert_eq!(summary.has_audio, has_audio_stream(path));
}

/// Build a 1080p timeline with one short video clip referencing `asset-1`.
fn build_timeline(frames: i32, src_w: i32, src_h: i32, src_fps: f64) -> Timeline {
    let mut tl = Timeline::new(); // 30fps / 1920x1080 by default
    tl.fps = src_fps.round() as i32;
    let mut track = Track::new("t1", ClipType::Video);
    let clip = Clip::new("clip-1", "asset-1", 0, frames);
    track.clips.push(clip);
    tl.tracks.push(track);
    // src dims are carried via the manifest entry, not the timeline.
    let _ = (src_w, src_h);
    tl
}

/// Build a manifest with one external video asset pointing at `media_path`.
fn build_manifest(media_path: &Path, src_w: i32, src_h: i32, src_fps: f64) -> MediaManifest {
    build_manifest_with_audio(media_path, src_w, src_h, src_fps, false)
}

/// Like [`build_manifest`] but lets the test declare whether the asset carries
/// an audio track (so the export's audio mixdown path is exercised).
fn build_manifest_with_audio(
    media_path: &Path,
    src_w: i32,
    src_h: i32,
    src_fps: f64,
    has_audio: bool,
) -> MediaManifest {
    let mut manifest = MediaManifest::new();
    manifest.entries.push(MediaManifestEntry {
        id: "asset-1".into(),
        name: "test.mp4".into(),
        kind: ClipType::Video,
        source: MediaSource::External {
            absolute_path: media_path.to_string_lossy().into_owned(),
        },
        duration: 1.0,
        generation_input: None,
        source_width: Some(src_w),
        source_height: Some(src_h),
        source_fps: Some(src_fps),
        has_audio: Some(has_audio),
        color: None,
        proxy: None,
        folder_id: None,
        cached_remote_url: None,
        cached_remote_url_expires_at: None,
    });
    manifest
}

// The orchestrator under test lives in the lib crate's `export` module
// (`pub mod export` / `pub fn run_export`). Integration tests compile against the
// `rlib` target, so we drive it directly. `opentake_tauri_lib` is the lib name
// (see `[lib] name` in src-tauri/Cargo.toml).
use opentake_tauri_lib::export::{run_export, ExportQuality, ExportRequest};

fn assert_preflight_rejects_source(
    timeline: &Timeline,
    manifest: &MediaManifest,
    out: &Path,
    expected_media_ref: &str,
) {
    let request = ExportRequest {
        out_path: out.to_string_lossy().into_owned(),
        codec: Default::default(),
        quality: ExportQuality::P720,
    };
    let error = run_export(timeline, manifest, &None, &request)
        .expect_err("unavailable media must fail before an output is created");
    assert!(
        error.contains(expected_media_ref),
        "error must identify the offending media: {error}"
    );
    assert!(!out.exists(), "failed preflight must not leave an output");
}

#[test]
fn export_rejects_missing_image_overlay_before_creating_output() {
    if !ffmpeg_ready() {
        eprintln!("skip: ffmpeg/ffprobe not available");
        return;
    }
    let dir = tempfile::tempdir().unwrap();
    let missing_image = dir.path().join("removed.png");
    let video = dir.path().join("background.mp4");
    assert!(make_video(&video, 64, 64, 10, 3));
    let mut timeline = build_timeline(3, 64, 64, 10.0);
    let mut overlay = Track::new("overlay", ClipType::Video);
    let mut image_clip = Clip::new("image", "image-2", 0, 3);
    image_clip.media_type = ClipType::Image;
    overlay.clips.push(image_clip);
    timeline.tracks.insert(0, overlay);
    let mut manifest = build_manifest(&video, 64, 64, 10.0);
    let mut image_entry = manifest.entries[0].clone();
    image_entry.id = "image-2".into();
    image_entry.name = "removed.png".into();
    image_entry.kind = ClipType::Image;
    image_entry.source = MediaSource::External {
        absolute_path: missing_image.to_string_lossy().into_owned(),
    };
    manifest.entries.push(image_entry);
    assert_preflight_rejects_source(&timeline, &manifest, &dir.path().join("out.mp4"), "image-2");
}

#[test]
fn export_rejects_missing_video_on_muted_track_before_creating_output() {
    let dir = tempfile::tempdir().unwrap();
    let mut timeline = build_timeline(3, 64, 64, 10.0);
    timeline.tracks[0].muted = true;
    let manifest = build_manifest(&dir.path().join("removed.mp4"), 64, 64, 10.0);
    assert_preflight_rejects_source(&timeline, &manifest, &dir.path().join("out.mp4"), "asset-1");
}

#[test]
fn export_rejects_corrupt_video_before_creating_output() {
    if !ffmpeg_ready() {
        eprintln!("skip: ffmpeg/ffprobe not available");
        return;
    }
    let dir = tempfile::tempdir().unwrap();
    let corrupt = dir.path().join("broken.mp4");
    std::fs::write(&corrupt, b"not a playable video stream").unwrap();
    let timeline = build_timeline(3, 64, 64, 10.0);
    let manifest = build_manifest(&corrupt, 64, 64, 10.0);
    assert_preflight_rejects_source(&timeline, &manifest, &dir.path().join("out.mp4"), "asset-1");
}

#[test]
fn export_rejects_missing_audible_source_before_creating_output() {
    let dir = tempfile::tempdir().unwrap();
    let timeline = build_timeline(3, 64, 64, 10.0);
    let manifest = build_manifest_with_audio(&dir.path().join("removed.mp4"), 64, 64, 10.0, true);
    assert_preflight_rejects_source(&timeline, &manifest, &dir.path().join("out.mp4"), "asset-1");
}

#[test]
fn export_full_timeline_produces_playable_mp4() {
    if !ffmpeg_ready() {
        eprintln!("skip: ffmpeg/ffprobe not available");
        return;
    }

    let dir = tempfile::tempdir().unwrap();
    let src = dir.path().join("src.mp4");
    let out = dir.path().join("out.mp4");

    // Source: 320x240 @ 10fps, 6 frames (0.6s). Small + fast.
    let (sw, sh, sfps, frames) = (320, 240, 10, 6);
    if !make_video(&src, sw, sh, sfps, frames) {
        eprintln!("skip: could not generate fixture media");
        return;
    }

    let timeline = build_timeline(frames as i32, sw as i32, sh as i32, sfps as f64);
    let manifest = build_manifest(&src, sw as i32, sh as i32, sfps as f64);

    let req = ExportRequest {
        out_path: out.to_string_lossy().into_owned(),
        codec: Default::default(), // H.264
        quality: ExportQuality::P720,
    };

    let summary = match run_export(&timeline, &manifest, &None, &req) {
        Ok(s) => s,
        Err(e) => {
            // The most common offline cause is no GPU adapter; treat that as a
            // skip rather than a hard failure (matches the ffmpeg auto-skip).
            if e.contains("no GPU device") {
                eprintln!("skip: no GPU adapter available ({e})");
                return;
            }
            panic!("export failed: {e}");
        }
    };

    // 1080p export of a 320x240 (4:3) source: short side 240 → 720 → scale 3.0,
    // so 960x720 (export_render_size scales the canvas, not the source). The
    // canvas is the timeline's 1920x1080 though, so short side 1080 → 720 →
    // 1280x720. Assert against what the orchestrator reported and what ffprobe
    // reads back — they must agree.
    assert!(out.exists(), "output file should exist");
    assert_eq!(summary.frame_count, frames as i32);
    assert_eq!(summary.fps, sfps as i32);
    assert_summary_matches_real_probe(&summary, &out);

    let pw: u32 = probe_field(&out, "stream=width").unwrap().parse().unwrap();
    let ph: u32 = probe_field(&out, "stream=height").unwrap().parse().unwrap();
    assert_eq!(pw, summary.width, "probed width matches reported");
    assert_eq!(ph, summary.height, "probed height matches reported");
    assert!(
        pw.is_multiple_of(2) && ph.is_multiple_of(2),
        "encoded dims are even"
    );

    let codec = probe_field(&out, "stream=codec_name").unwrap();
    assert_eq!(codec, "h264", "codec should be H.264");

    let nframes = probe_frame_count(&out).unwrap();
    assert_eq!(
        nframes, frames as u64,
        "encoded frame count matches timeline"
    );

    // The video-only source has no audio track → export stays video-only.
    assert!(
        !has_audio_stream(&out),
        "video-only timeline must not gain an audio stream"
    );
}

/// Regression for the packaged HDR export producing a valid-looking but fully
/// black H.264 file. The packaged FFmpeg and the developer FFmpeg can expose
/// different HDR filter backends, so this test is also run with
/// `OPENTAKE_FFMPEG`/`OPENTAKE_FFPROBE` pointed at the bundled sidecars.
#[test]
fn export_hdr_timeline_preserves_picture_contrast_and_delivers_bt709() {
    if !ffmpeg_ready() {
        eprintln!("skip: ffmpeg/ffprobe not available");
        return;
    }

    let dir = tempfile::tempdir().unwrap();
    let src = dir.path().join("hdr-pq.mp4");
    let out = dir.path().join("hdr-delivery.mp4");
    let (sw, sh, sfps, frames) = (160, 90, 12, 12);
    if !make_hdr_video(&src, sw, sh, sfps, frames) {
        eprintln!("skip: could not generate HDR fixture media");
        return;
    }

    let timeline = build_timeline(frames as i32, sw as i32, sh as i32, sfps as f64);
    let mut manifest = build_manifest(&src, sw as i32, sh as i32, sfps as f64);
    manifest.entries[0].color = Some(MediaColorMetadata {
        primaries: Some("bt2020".into()),
        transfer: Some("smpte2084".into()),
        matrix: Some("bt2020nc".into()),
        range: Some("tv".into()),
    });

    let request = ExportRequest {
        out_path: out.to_string_lossy().into_owned(),
        codec: Default::default(),
        quality: ExportQuality::P720,
    };
    let summary = match run_export(&timeline, &manifest, &None, &request) {
        Ok(summary) => summary,
        Err(error) if error.contains("no GPU device") => {
            eprintln!("skip: no GPU adapter available ({error})");
            return;
        }
        Err(error) => panic!("HDR export failed: {error}"),
    };

    assert_summary_matches_real_probe(&summary, &out);
    assert_eq!(
        probe_field(&out, "stream=color_primaries").as_deref(),
        Some("bt709")
    );
    assert_eq!(
        probe_field(&out, "stream=color_transfer").as_deref(),
        Some("bt709")
    );
    assert_eq!(
        probe_field(&out, "stream=color_space").as_deref(),
        Some("bt709")
    );
    let (minimum, maximum) = decoded_rgb_range(&out).expect("decode exported first frame");
    assert!(
        maximum.saturating_sub(minimum) > 32,
        "tone-mapped export must retain picture contrast, got RGB range {minimum}..={maximum}"
    );
}

/// Regression for "export video crashes the app": the render device was created
/// with `downlevel_defaults()` limits (max_texture_dimension_2d = 2048), so a
/// full-resolution export above 2048px (2K / 4K) blew up inside
/// `Device::create_texture` with an uncaptured wgpu error that panics → SIGABRT.
/// A 4K-quality export renders a target far beyond 2048px and must now succeed.
#[test]
fn export_4k_render_target_clears_downlevel_texture_limit() {
    if !ffmpeg_ready() {
        eprintln!("skip: ffmpeg/ffprobe not available");
        return;
    }

    let dir = tempfile::tempdir().unwrap();
    let src = dir.path().join("src4k.mp4");
    let out = dir.path().join("out4k.mp4");

    let (sw, sh, sfps, frames) = (320, 240, 10, 4);
    if !make_video(&src, sw, sh, sfps, frames) {
        eprintln!("skip: could not generate fixture media");
        return;
    }

    let timeline = build_timeline(frames as i32, sw as i32, sh as i32, sfps as f64);
    let manifest = build_manifest(&src, sw as i32, sh as i32, sfps as f64);

    let req = ExportRequest {
        out_path: out.to_string_lossy().into_owned(),
        codec: Default::default(),
        quality: ExportQuality::P4k,
    };

    let summary = match run_export(&timeline, &manifest, &None, &req) {
        Ok(s) => s,
        Err(e) => {
            if e.contains("no GPU device") {
                eprintln!("skip: no GPU adapter available ({e})");
                return;
            }
            panic!("export failed: {e}");
        }
    };

    assert!(out.exists(), "4K output file should exist");
    assert_summary_matches_real_probe(&summary, &out);
    // The render target / encode exceeds the old 2048 cap on at least one axis.
    assert!(
        summary.width > 2048 || summary.height > 2048,
        "4K export should clear the old 2048 texture cap (got {}x{})",
        summary.width,
        summary.height
    );
}

#[test]
fn export_with_audio_clip_mux_aac_stream() {
    if !ffmpeg_ready() {
        eprintln!("skip: ffmpeg/ffprobe not available");
        return;
    }

    let dir = tempfile::tempdir().unwrap();
    let src = dir.path().join("src_audio.mp4");
    let out = dir.path().join("out_audio.mp4");

    // Source: 320x240 @ 10fps, 10 frames (1.0s), WITH a 440 Hz sine track.
    let (sw, sh, sfps, frames) = (320u32, 240u32, 10u32, 10u32);
    if !make_video_with_audio(&src, sw, sh, sfps, frames) {
        eprintln!("skip: could not generate audio fixture media");
        return;
    }
    // Sanity: the fixture really has audio (else the assertion below is vacuous).
    if !has_audio_stream(&src) {
        eprintln!("skip: fixture lacks an audio stream");
        return;
    }

    let timeline = build_timeline(frames as i32, sw as i32, sh as i32, sfps as f64);
    let manifest = build_manifest_with_audio(&src, sw as i32, sh as i32, sfps as f64, true);

    let req = ExportRequest {
        out_path: out.to_string_lossy().into_owned(),
        codec: Default::default(), // H.264 → AAC audio
        quality: ExportQuality::P720,
    };

    let summary = match run_export(&timeline, &manifest, &None, &req) {
        Ok(s) => s,
        Err(e) => {
            if e.contains("no GPU device") {
                eprintln!("skip: no GPU adapter available ({e})");
                return;
            }
            panic!("export failed: {e}");
        }
    };

    assert!(out.exists(), "output file should exist");
    assert_eq!(summary.frame_count, frames as i32);
    assert_summary_matches_real_probe(&summary, &out);

    // Video stream is still H.264 at the reported size.
    let vcodec = probe_field(&out, "stream=codec_name").unwrap();
    assert_eq!(vcodec, "h264", "video codec should be H.264");

    // The mixdown muxed an audio stream into the container.
    assert!(
        has_audio_stream(&out),
        "audio-bearing timeline must produce an audio stream"
    );

    // The muxed audio codec is AAC (H.264 preset's `-c:a aac`).
    let acodec = Command::new("ffprobe")
        .args([
            "-v",
            "error",
            "-select_streams",
            "a:0",
            "-show_entries",
            "stream=codec_name",
            "-of",
            "default=noprint_wrappers=1:nokey=1",
        ])
        .arg(&out)
        .output()
        .ok()
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string());
    assert_eq!(acodec.as_deref(), Some("aac"), "muxed audio should be AAC");

    // The temp mux artifacts are cleaned up (no `.tmp` siblings left behind).
    let leftover_video = dir.path().join("out_audio.mp4.video.tmp");
    let leftover_pcm = dir.path().join("out_audio.mp4.pcm.tmp");
    assert!(!leftover_video.exists(), "video temp should be removed");
    assert!(!leftover_pcm.exists(), "pcm temp should be removed");
}

/// A text-bearing timeline must export end-to-end when system fonts exist and
/// be rejected up front when they do not (the fail-closed font guard added for
/// the "invisible text" audit finding). Auto-skips when ffmpeg/ffprobe, the
/// GPU, or fonts are unavailable, matching the other export tests.
#[test]
fn export_with_text_clip_respects_font_availability() {
    if !ffmpeg_ready() {
        eprintln!("skip: ffmpeg/ffprobe not available");
        return;
    }

    let dir = tempfile::tempdir().unwrap();
    let src = dir.path().join("src_text.mp4");
    let out = dir.path().join("out_text.mp4");

    let (sw, sh, sfps, frames) = (320, 240, 10, 6);
    if !make_video(&src, sw, sh, sfps, frames) {
        eprintln!("skip: could not generate fixture media");
        return;
    }

    let mut timeline = build_timeline(frames as i32, sw as i32, sh as i32, sfps as f64);
    let mut text_track = Track::new("t-text", ClipType::Video);
    let mut text = Clip::new("clip-text", "", 0, frames as i32);
    text.media_type = ClipType::Text;
    text.source_clip_type = ClipType::Text;
    text.text_content = Some("integration probe text".to_string());
    text.text_style = Some(TextStyle::default());
    text_track.clips.push(text);
    timeline.tracks.push(text_track);
    let manifest = build_manifest(&src, sw as i32, sh as i32, sfps as f64);

    let req = ExportRequest {
        out_path: out.to_string_lossy().into_owned(),
        codec: Default::default(), // H.264
        quality: ExportQuality::P720,
    };
    match run_export(&timeline, &manifest, &None, &req) {
        Ok(summary) => {
            assert!(out.exists(), "output file should exist");
            assert_eq!(summary.frame_count, frames as i32);
            assert_summary_matches_real_probe(&summary, &out);
        }
        Err(error) if error.contains("no GPU device") || error.contains("no system fonts") => {
            // No GPU adapter or a fontless headless runner: the font guard
            // rejected the export by design — same auto-skip semantics as the
            // ffmpeg/GPU guards above.
            eprintln!("skip: {error}");
        }
        Err(error) => panic!("text export failed: {error}"),
    }
}

/// Transparent delivery must preserve the alpha plane through the full GPU →
/// raw-RGBA → ProRes 4444 path. The text glyph gives the frame a non-zero alpha
/// island while the transparent clear color leaves the surrounding canvas at 0.
#[test]
fn export_prores_4444_preserves_transparent_text_alpha() {
    if !ffmpeg_ready() {
        eprintln!("skip: ffmpeg/ffprobe not available");
        return;
    }

    let dir = tempfile::tempdir().unwrap();
    let out = dir.path().join("transparent-text.mov");
    let frames = 6;
    let mut timeline = Timeline::new();
    timeline.fps = 10;
    let mut text_track = Track::new("t-alpha-text", ClipType::Video);
    let mut text = Clip::new("clip-alpha-text", "", 0, frames);
    text.media_type = ClipType::Text;
    text.source_clip_type = ClipType::Text;
    text.text_content = Some("alpha integration probe".to_string());
    text.text_style = Some(TextStyle::default());
    text_track.clips.push(text);
    timeline.tracks.push(text_track);

    let req = ExportRequest {
        out_path: out.to_string_lossy().into_owned(),
        codec: opentake_tauri_lib::export::ExportCodec::Prores4444,
        quality: ExportQuality::P720,
    };
    let manifest = MediaManifest::new();
    let summary = match run_export(&timeline, &manifest, &None, &req) {
        Ok(summary) => summary,
        Err(error) if error.contains("no GPU device") || error.contains("no system fonts") => {
            eprintln!("skip: {error}");
            return;
        }
        Err(error) => panic!("transparent ProRes export failed: {error}"),
    };

    assert_eq!(summary.frame_count, frames);
    assert_eq!(
        probe_field(&out, "stream=codec_name").as_deref(),
        Some("prores")
    );
    assert!(
        matches!(
            probe_field(&out, "stream=pix_fmt").as_deref(),
            Some("yuva444p10le" | "yuva444p12le")
        ),
        "ProRes 4444 should retain a yuva444 pixel format"
    );
    let (minimum, maximum) = decoded_alpha_range(&out).expect("decode alpha plane");
    assert_eq!(minimum, 0, "transparent canvas should retain zero alpha");
    assert!(maximum > 0, "text glyph should contribute non-zero alpha");
}
