//! ffmpeg + GPU gated integration test for the streaming playback render loop
//! (`playback::RenderLoop`).
//!
//! Builds a short video clip (and a two-track variant), drives the render loop's
//! `render_frame` directly (no thread/clock so the test is deterministic), and
//! asserts it composites real, non-black, animating frames and survives a seek.
//!
//! Gated behind the `playback-engine` feature (the module only exists then) AND
//! auto-skips when ffmpeg/ffprobe are missing or no GPU adapter is available, so
//! the default `cargo test` stays green offline. Nothing is downloaded — fixtures
//! are generated by ffmpeg's lavfi `testsrc`.
#![cfg(feature = "playback-engine")]

use std::path::Path;
use std::process::Command;
use std::sync::atomic::{AtomicI32, AtomicUsize, Ordering};
use std::sync::{mpsc, Arc, Mutex};
use std::thread::{self, sleep};
use std::time::{Duration, Instant};

use opentake_domain::{
    Clip, ClipType, MediaManifest, MediaManifestEntry, MediaSource, Timeline, Track,
};
use opentake_media::{decode_frame_at, FrameRequest, MediaCancelToken};
use opentake_render::{DecodedFrame, RenderSize};
use opentake_tauri_lib::playback::engine::BoundedReaper;
use opentake_tauri_lib::playback::{
    project_media, project_text, FrameSink, InstantClock, PlaybackClock, PlaybackEngine,
    PlayheadEmitter, RenderLoop,
};

/// Warm-up budget: the decode worker is a separate thread/process, so the first
/// `render_frame(target)` can be black until ffmpeg produces that frame. 200 ×
/// 10ms = ~2s, ample for a 320×240 `testsrc` frame.
const WARMUP_TRIES: usize = 200;
const WARMUP_SLEEP: Duration = Duration::from_millis(10);

fn ffmpeg_ready() -> bool {
    Command::new("ffmpeg")
        .arg("-version")
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false)
}

/// Generate an N-frame `testsrc` video at `path`. Returns false (→ skip) on
/// failure. `hue` shifts the palette so two assets differ visibly.
fn make_video(path: &Path, w: u32, h: u32, fps: u32, frames: u32, hue: i32) -> bool {
    let dur = frames as f64 / fps as f64;
    Command::new("ffmpeg")
        .args([
            "-v",
            "error",
            "-f",
            "lavfi",
            "-i",
            &format!("testsrc=duration={dur}:size={w}x{h}:rate={fps}"),
            "-vf",
            &format!("hue=h={hue}"),
            "-c:v",
            "libx264",
            "-pix_fmt",
            "yuv420p",
            "-y",
        ])
        .arg(path)
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}

fn make_distinct_cfr_video(path: &Path, w: u32, h: u32, fps: u32, frames: u32) {
    let output = Command::new("ffmpeg")
        .args([
            "-v",
            "error",
            "-f",
            "lavfi",
            "-i",
            &format!("testsrc2=size={w}x{h}:rate={fps}"),
            "-frames:v",
            &frames.to_string(),
            "-c:v",
            "libx264",
            "-g",
            &frames.to_string(),
            "-keyint_min",
            &frames.to_string(),
            "-sc_threshold",
            "0",
            "-pix_fmt",
            "yuv420p",
            "-fps_mode",
            "cfr",
            "-y",
        ])
        .arg(path)
        .output()
        .expect("required ffmpeg must start for exact-bootstrap fixture");
    assert!(
        output.status.success(),
        "generate exact-bootstrap CFR fixture: {}",
        String::from_utf8_lossy(&output.stderr)
    );
}

fn external_entry(id: &str, path: &Path, w: i32, h: i32, fps: f64) -> MediaManifestEntry {
    MediaManifestEntry {
        id: id.into(),
        name: format!("{id}.mp4"),
        kind: ClipType::Video,
        source: MediaSource::External {
            absolute_path: path.to_string_lossy().into_owned(),
        },
        duration: 1.0,
        generation_input: None,
        source_width: Some(w),
        source_height: Some(h),
        source_fps: Some(fps),
        has_audio: Some(false),
        color: None,
        proxy: None,
        folder_id: None,
        cached_remote_url: None,
        cached_remote_url_expires_at: None,
    }
}

/// Build a `RenderLoop`, mapping a `no GPU device` error to `None` (→ skip).
fn try_render_loop(
    timeline: Timeline,
    manifest: &MediaManifest,
    render_size: RenderSize,
) -> Option<RenderLoop> {
    let (sizes, media) = project_media(manifest, &None);
    let text = project_text(&timeline);
    match RenderLoop::new(timeline, media, text, sizes, render_size) {
        Ok(rl) => Some(rl),
        Err(e) if e.contains("no GPU device") => {
            eprintln!("skip: no GPU adapter available ({e})");
            None
        }
        Err(e) => panic!("render loop init failed: {e}"),
    }
}

fn has_visible_rgb(rgba: &[u8]) -> bool {
    rgba.as_chunks::<4>()
        .0
        .iter()
        .any(|pixel| pixel[0] != 0 || pixel[1] != 0 || pixel[2] != 0)
}

/// Render `target` repeatedly until the frame has a non-black RGB pixel.
fn render_until_content(rl: &mut RenderLoop, target: i32, w: u32, h: u32) -> Option<Vec<u8>> {
    for _ in 0..WARMUP_TRIES {
        let f = rl.render_frame(target).expect("render_frame");
        assert_eq!(f.width, w, "composite width matches render size");
        assert_eq!(f.height, h, "composite height matches render size");
        if has_visible_rgb(&f.rgba) {
            return Some(f.rgba);
        }
        sleep(WARMUP_SLEEP);
    }
    None
}

fn gpu_ready(render_size: RenderSize) -> bool {
    try_render_loop(Timeline::new(), &MediaManifest::new(), render_size).is_some()
}

struct ManualClock(AtomicI32);

impl ManualClock {
    fn new(frame: i32) -> Self {
        Self(AtomicI32::new(frame))
    }

    fn set(&self, frame: i32) {
        self.0.store(frame, Ordering::Release);
    }
}

impl PlaybackClock for ManualClock {
    fn frame(&self, _fps: i32) -> i32 {
        self.0.load(Ordering::Acquire)
    }

    fn seek(&self, frame: i32) {
        self.set(frame);
    }
}

#[test]
fn cold_bootstrap_uses_exact_trimmed_source_frame() {
    if !ffmpeg_ready() {
        eprintln!("skip: ffmpeg not available");
        return;
    }
    let dir = tempfile::tempdir().expect("fixture tempdir");
    let src = dir.path().join("distinct-cfr.mp4");
    let (w, h, fps, frames, source_frame) = (160u32, 90u32, 12u32, 12u32, 5i32);
    make_distinct_cfr_video(&src, w, h, fps, frames);

    let exact_request = |frame: i32| FrameRequest {
        time_secs: frame as f64 / fps as f64,
        max_size: (w, h),
        apply_rotation: true,
    };
    let (_, predecessor) = decode_frame_at(&src, &exact_request(source_frame - 1))
        .expect("decode predecessor fixture frame");
    let (_, target) =
        decode_frame_at(&src, &exact_request(source_frame)).expect("decode target fixture frame");
    assert_ne!(
        target.rgba, predecessor.rgba,
        "CFR fixture must have distinct adjacent frame pixels"
    );

    let mut timeline = Timeline::new();
    timeline.fps = fps as i32;
    let mut track = Track::new("t1", ClipType::Video);
    let mut clip = Clip::new("clip-1", "asset-1", 0, frames as i32 - source_frame);
    clip.trim_start_frame = source_frame;
    track.clips.push(clip);
    timeline.tracks.push(track);
    let mut manifest = MediaManifest::new();
    manifest.entries.push(external_entry(
        "asset-1", &src, w as i32, h as i32, fps as f64,
    ));

    let Some(mut render_loop) = try_render_loop(timeline, &manifest, RenderSize::new(w, h)) else {
        return;
    };
    let first = render_loop
        .render_frame(0)
        .expect("cold bootstrap must render the trimmed source frame");

    assert_eq!(first.rgba, target.rgba, "first composite must match target");
    assert_ne!(
        first.rgba, predecessor.rgba,
        "first composite must not use the predecessor"
    );
}

#[test]
fn cold_bootstrap_decode_failure_is_reported_instead_of_publishing_black() {
    let dir = tempfile::tempdir().expect("fixture tempdir");
    let missing = dir.path().join("missing.mp4");
    let (w, h, fps) = (160u32, 90u32, 12u32);

    let mut timeline = Timeline::new();
    timeline.fps = fps as i32;
    let mut track = Track::new("t1", ClipType::Video);
    let mut clip = Clip::new("clip-1", "asset-1", 0, 3);
    clip.trim_start_frame = 4;
    track.clips.push(clip);
    timeline.tracks.push(track);
    let mut manifest = MediaManifest::new();
    manifest.entries.push(external_entry(
        "asset-1", &missing, w as i32, h as i32, fps as f64,
    ));

    let Some(mut render_loop) = try_render_loop(timeline, &manifest, RenderSize::new(w, h)) else {
        return;
    };
    let error = match render_loop.render_frame(0) {
        Ok(frame) => panic!(
            "cold bootstrap decode failure published {}x{} black frame",
            frame.width, frame.height
        ),
        Err(error) => error,
    };
    assert!(
        error.contains("bootstrap") && error.contains("asset-1"),
        "error must identify bootstrap media failure: {error}"
    );
}

#[test]
fn missing_image_materialization_reaches_render_loop_instead_of_publishing_black() {
    let dir = tempfile::tempdir().expect("fixture tempdir");
    let missing = dir.path().join("missing.png");
    let (w, h) = (64i32, 64i32);

    let mut timeline = Timeline::new();
    timeline.fps = 30;
    let mut track = Track::new("t1", ClipType::Video);
    let mut clip = Clip::new("clip-1", "asset-1", 0, 3);
    clip.media_type = ClipType::Image;
    clip.source_clip_type = ClipType::Image;
    track.clips.push(clip);
    timeline.tracks.push(track);
    let mut manifest = MediaManifest::new();
    manifest.entries.push(MediaManifestEntry {
        id: "asset-1".into(),
        name: "missing.png".into(),
        kind: ClipType::Image,
        source: MediaSource::External {
            absolute_path: missing.to_string_lossy().into_owned(),
        },
        duration: 1.0,
        generation_input: None,
        source_width: Some(w),
        source_height: Some(h),
        source_fps: None,
        has_audio: Some(false),
        color: None,
        proxy: None,
        folder_id: None,
        cached_remote_url: None,
        cached_remote_url_expires_at: None,
    });

    let Some(mut render_loop) = try_render_loop(timeline, &manifest, RenderSize::new(64, 64))
    else {
        return;
    };
    let error = render_loop
        .render_frame(0)
        .expect_err("missing image must not publish a successful black frame");
    assert!(
        error.contains("playback materialization failed") && error.contains("asset-1"),
        "error must identify playback materialization failure: {error}"
    );
}

#[test]
fn cancelling_initial_ready_bootstrap_releases_the_readiness_worker() {
    if !ffmpeg_ready() {
        eprintln!("skip: ffmpeg not available");
        return;
    }
    if !gpu_ready(RenderSize::new(2, 2)) {
        return;
    }
    let dir = tempfile::tempdir().expect("fixture tempdir");
    let fifo = dir.path().join("blocked-initial-source");
    let status = Command::new("mkfifo")
        .arg(&fifo)
        .status()
        .expect("mkfifo must start");
    assert!(status.success(), "mkfifo must create the blocked source");

    let mut timeline = Timeline::new();
    timeline.fps = 30;
    let mut track = Track::new("t1", ClipType::Video);
    track.clips.push(Clip::new("clip-1", "asset-1", 0, 4));
    timeline.tracks.push(track);
    let mut manifest = MediaManifest::new();
    manifest
        .entries
        .push(external_entry("asset-1", &fifo, 2, 2, 30.0));
    let (sizes, media) = project_media(&manifest, &None);
    let text = project_text(&timeline);

    struct NoopSink;
    impl FrameSink for NoopSink {
        fn push_frame(&self, _frame: &DecodedFrame) {}
    }
    struct NoopEmitter;
    impl PlayheadEmitter for NoopEmitter {
        fn emit(&self, _frame: i32) {}
    }

    let cancel = MediaCancelToken::new();
    let ready_cancel = cancel.clone();
    let (ready_tx, ready_rx) = mpsc::channel();
    thread::spawn(move || {
        let result = PlaybackEngine::spawn_ready_cancellable(
            timeline,
            media,
            text,
            sizes,
            RenderSize::new(2, 2),
            Arc::new(ManualClock::new(0)),
            Arc::new(NoopSink),
            Arc::new(NoopEmitter),
            0,
            ready_cancel,
        );
        let _ = ready_tx.send(result.map(|engine| engine.stop()));
    });

    let spawn_deadline = Instant::now() + Duration::from_secs(3);
    while cancel.spawned_child_count() == 0 && Instant::now() < spawn_deadline {
        sleep(Duration::from_millis(10));
    }
    assert_eq!(
        cancel.spawned_child_count(),
        1,
        "initial exact bootstrap must reach the blocked ffmpeg child"
    );

    cancel.cancel();
    let error = ready_rx
        .recv_timeout(Duration::from_secs(3))
        .expect("external cancellation must release spawn_ready")
        .expect_err("cancelled initial readiness must not install an engine");
    assert!(
        error.contains("cancelled"),
        "typed cause must survive: {error}"
    );
    assert_eq!(
        cancel.active_reader_count(),
        0,
        "cancelled initial bootstrap must join its event reader"
    );
}

#[test]
fn stopping_running_engine_cancels_blocked_cold_bootstrap() {
    if !ffmpeg_ready() {
        eprintln!("skip: ffmpeg not available");
        return;
    }
    if !gpu_ready(RenderSize::new(2, 2)) {
        return;
    }
    let dir = tempfile::tempdir().expect("fixture tempdir");
    let fifo = dir.path().join("blocked-source");
    let status = Command::new("mkfifo")
        .arg(&fifo)
        .status()
        .expect("mkfifo must start");
    assert!(
        status.success(),
        "mkfifo must create the blocked media source"
    );

    let mut timeline = Timeline::new();
    timeline.fps = 30;
    let mut track = Track::new("t1", ClipType::Video);
    track.clips.push(Clip::new("clip-1", "asset-1", 1, 4));
    timeline.tracks.push(track);
    let mut manifest = MediaManifest::new();
    manifest
        .entries
        .push(external_entry("asset-1", &fifo, 2, 2, 30.0));
    let (sizes, media) = project_media(&manifest, &None);
    let text = project_text(&timeline);

    struct NoopSink;
    impl FrameSink for NoopSink {
        fn push_frame(&self, _frame: &DecodedFrame) {}
    }
    struct NoopEmitter;
    impl PlayheadEmitter for NoopEmitter {
        fn emit(&self, _frame: i32) {}
    }

    let clock = Arc::new(ManualClock::new(0));
    let engine = PlaybackEngine::spawn_ready(
        timeline,
        media,
        text,
        sizes,
        RenderSize::new(2, 2),
        clock.clone(),
        Arc::new(NoopSink),
        Arc::new(NoopEmitter),
        0,
    )
    .expect("frame zero prepares before the clip becomes visible");
    engine.resume(0).expect("resume prepared engine");
    clock.set(1);
    sleep(Duration::from_millis(250));

    let reaper = BoundedReaper::new();
    let render_permit = reaper
        .try_reserve()
        .expect("reserve the blocked engine teardown");
    let dummy_permit = reaper
        .try_reserve()
        .expect("reserve the second bounded teardown slot");
    assert!(
        reaper.try_reserve().is_err(),
        "both teardown slots must be occupied before cancellation"
    );

    let render_handle = engine
        .request_stop()
        .expect("running engine owns a render handle");
    let joined = Arc::new(Mutex::new(None));
    let joined_result = Arc::clone(&joined);
    let join_wrapper = thread::spawn(move || {
        *joined_result
            .lock()
            .unwrap_or_else(|poisoned| poisoned.into_inner()) = Some(render_handle.join().is_ok());
    });
    render_permit
        .enqueue(vec![join_wrapper])
        .expect("enqueue cancelled render handle");

    let (dummy_release_tx, dummy_release_rx) = mpsc::channel();
    let dummy_handle = thread::spawn(move || {
        let _ = dummy_release_rx.recv();
    });
    dummy_permit
        .enqueue(vec![dummy_handle])
        .expect("enqueue held second teardown");

    let deadline = Instant::now() + Duration::from_secs(3);
    let recovered = loop {
        match reaper.try_reserve() {
            Ok(permit) => break permit,
            Err(_) if Instant::now() < deadline => sleep(Duration::from_millis(10)),
            Err(error) => panic!("cancelled bootstrap did not recover reaper capacity: {error}"),
        }
    };
    assert!(
        joined
            .lock()
            .unwrap_or_else(|poisoned| poisoned.into_inner())
            .is_some_and(|ok| ok),
        "render thread must not panic during cancellation"
    );
    drop(recovered);
    dummy_release_tx
        .send(())
        .expect("release held teardown slot");
}

#[test]
fn render_loop_streams_frames_advances_and_seeks() {
    if !ffmpeg_ready() {
        eprintln!("skip: ffmpeg not available");
        return;
    }
    let dir = tempfile::tempdir().unwrap();
    let src = dir.path().join("src.mp4");
    let (w, h, fps, frames) = (320u32, 240u32, 10u32, 12u32);
    if !make_video(&src, w, h, fps, frames, 0) {
        eprintln!("skip: could not generate fixture media");
        return;
    }

    let mut tl = Timeline::new();
    tl.fps = fps as i32;
    let mut track = Track::new("t1", ClipType::Video);
    track
        .clips
        .push(Clip::new("clip-1", "asset-1", 0, frames as i32));
    tl.tracks.push(track);
    let mut manifest = MediaManifest::new();
    manifest.entries.push(external_entry(
        "asset-1", &src, w as i32, h as i32, fps as f64,
    ));

    let size = RenderSize::new(w, h);
    let Some(mut rl) = try_render_loop(tl, &manifest, size) else {
        return;
    };
    assert_eq!(rl.total_frames(), frames as i32);
    assert_eq!(rl.fps(), fps as i32);

    // spawn_ready may publish only a complete first frame, never the compositor
    // clear that the non-blocking stream returns during cold decoder startup.
    let frame0 = rl.render_frame(0).expect("render_frame(0)");
    assert!(
        has_visible_rgb(&frame0.rgba),
        "frame 0 should be visible on the first render"
    );
    let frame0 = frame0.rgba;

    // A later frame differs (testsrc animates a moving pattern + timestamp).
    let mut differs = false;
    for _ in 0..WARMUP_TRIES {
        let f = rl.render_frame(8).expect("render_frame(8)");
        if has_visible_rgb(&f.rgba) && f.rgba != frame0 {
            differs = true;
            break;
        }
        sleep(WARMUP_SLEEP);
    }
    assert!(differs, "a later frame should differ from frame 0");

    // Seek restarts the decode streams and still composites frame 0.
    rl.seek();
    let after_seek = render_until_content(&mut rl, 0, w, h)
        .expect("frame 0 should composite again after a seek");
    assert!(after_seek.iter().any(|&b| b != 0));
}

#[test]
fn render_loop_composites_two_tracks_concurrently() {
    if !ffmpeg_ready() {
        eprintln!("skip: ffmpeg not available");
        return;
    }
    let dir = tempfile::tempdir().unwrap();
    let src_a = dir.path().join("a.mp4");
    let src_b = dir.path().join("b.mp4");
    let (w, h, fps, frames) = (320u32, 240u32, 10u32, 12u32);
    // Two visibly different sources (hue-shifted) to exercise two concurrent,
    // independently-keyed (by clip id) decode streams.
    if !make_video(&src_a, w, h, fps, frames, 0) || !make_video(&src_b, w, h, fps, frames, 120) {
        eprintln!("skip: could not generate fixture media");
        return;
    }

    let mut tl = Timeline::new();
    tl.fps = fps as i32;
    let mut t1 = Track::new("t1", ClipType::Video);
    t1.clips
        .push(Clip::new("clip-1", "asset-1", 0, frames as i32));
    let mut t2 = Track::new("t2", ClipType::Video);
    t2.clips
        .push(Clip::new("clip-2", "asset-2", 0, frames as i32));
    tl.tracks.push(t1);
    tl.tracks.push(t2);

    let mut manifest = MediaManifest::new();
    manifest.entries.push(external_entry(
        "asset-1", &src_a, w as i32, h as i32, fps as f64,
    ));
    manifest.entries.push(external_entry(
        "asset-2", &src_b, w as i32, h as i32, fps as f64,
    ));

    let size = RenderSize::new(w, h);
    let Some(mut rl) = try_render_loop(tl, &manifest, size) else {
        return;
    };

    // Both clips are active at frame 0 → two concurrent streams; the composite
    // must come back with real content (no panic, no all-black).
    let composed = render_until_content(&mut rl, 0, w, h)
        .expect("two-track composite should render non-black within the warm-up budget");
    assert!(has_visible_rgb(&composed));
}

/// The threaded `PlaybackEngine` end-to-end: spawn it over a real GPU + ffmpeg
/// with an `InstantClock` and in-memory sink/emitter, let the wall clock advance
/// the playhead, and assert frames + the playhead reach the traits before `stop`
/// joins the render thread. Covers the thread loop the RenderLoop tests don't.
#[test]
fn playback_engine_thread_streams_frames_to_sink_and_emitter() {
    if !ffmpeg_ready() {
        eprintln!("skip: ffmpeg not available");
        return;
    }
    let dir = tempfile::tempdir().unwrap();
    let src = dir.path().join("src.mp4");
    let (w, h, fps, frames) = (320u32, 240u32, 10u32, 12u32);
    if !make_video(&src, w, h, fps, frames, 0) {
        eprintln!("skip: could not generate fixture media");
        return;
    }

    let mut tl = Timeline::new();
    tl.fps = fps as i32;
    let mut track = Track::new("t1", ClipType::Video);
    track
        .clips
        .push(Clip::new("clip-1", "asset-1", 0, frames as i32));
    tl.tracks.push(track);
    let mut manifest = MediaManifest::new();
    manifest.entries.push(external_entry(
        "asset-1", &src, w as i32, h as i32, fps as f64,
    ));

    let size = RenderSize::new(w, h);
    // Skip when no GPU adapter (the engine thread would otherwise just exit
    // internally and the assertions below couldn't distinguish that from a bug).
    if try_render_loop(tl.clone(), &manifest, size).is_none() {
        return;
    }

    let (sizes, media) = project_media(&manifest, &None);
    let text = project_text(&tl);

    let frame_count = Arc::new(AtomicUsize::new(0));
    let first_frame = Arc::new(Mutex::new(None::<Vec<u8>>));
    let last_emitted = Arc::new(AtomicI32::new(-1));

    struct CountingSink {
        count: Arc<AtomicUsize>,
        first_frame: Arc<Mutex<Option<Vec<u8>>>>,
    }
    impl FrameSink for CountingSink {
        fn push_frame(&self, frame: &DecodedFrame) {
            self.count.fetch_add(1, Ordering::Relaxed);
            let mut first = self
                .first_frame
                .lock()
                .unwrap_or_else(|poisoned| poisoned.into_inner());
            if first.is_none() {
                *first = Some(frame.rgba.clone());
            }
        }
    }
    struct RecordingEmitter(Arc<AtomicI32>);
    impl PlayheadEmitter for RecordingEmitter {
        fn emit(&self, frame: i32) {
            self.0.store(frame, Ordering::Relaxed);
        }
    }

    let clock: Arc<dyn PlaybackClock> = Arc::new(InstantClock::new(0));
    let sink: Arc<dyn FrameSink> = Arc::new(CountingSink {
        count: frame_count.clone(),
        first_frame: first_frame.clone(),
    });
    let emitter: Arc<dyn PlayheadEmitter> = Arc::new(RecordingEmitter(last_emitted.clone()));

    let engine = PlaybackEngine::spawn_ready(tl, media, text, sizes, size, clock, sink, emitter, 0)
        .expect("engine prepares first frame");
    assert_eq!(frame_count.load(Ordering::Relaxed), 0);
    engine.resume(0).expect("install publishes buffered frame");
    let produced = frame_count.load(Ordering::Relaxed) > 0;
    engine.stop();

    assert!(produced, "the engine thread produced no frames");
    assert!(
        first_frame
            .lock()
            .unwrap_or_else(|poisoned| poisoned.into_inner())
            .as_ref()
            .is_some_and(|rgba| has_visible_rgb(rgba)),
        "the engine's first publication must be visible"
    );
    assert!(
        last_emitted.load(Ordering::Relaxed) >= 0,
        "the engine thread emitted no playhead frame"
    );
}
