//! ffmpeg-backed integration tests for the decode/probe/pcm/thumbnail/waveform
//! and encode round-trip paths.
//!
//! These verify the chosen `ffmpeg-sidecar` (CLI) backend works end-to-end with
//! the locally installed ffmpeg (8.1 here). They **auto-skip** when ffmpeg /
//! ffprobe are not on `PATH`, so the default `cargo test` stays green and offline
//! on machines without ffmpeg — the test fixtures are generated by ffmpeg itself
//! (lavfi sources), so nothing is downloaded.

use std::path::Path;
use std::process::Command;

use opentake_media::decode::spawn_video_stream;
use opentake_media::ffmpeg_status::{ffmpeg_available, ffmpeg_path, ffprobe_available};
use opentake_media::{
    decode_frame_at, decode_frame_file_at_cancellable, decode_frames_at, encode, extract_pcm,
    probe, video_thumbnails, waveform, ExportPreset, ExportResolution, FrameRequest, PcmFormat,
    PcmSpec, RgbaFrame, VideoCodec, VideoEncoder, VideoStreamRequest,
};

/// Generate a 2 s 320x240@10fps test video with a 440 Hz sine audio track.
fn make_av(path: &Path) -> bool {
    Command::new("ffmpeg")
        .args([
            "-v",
            "error",
            "-f",
            "lavfi",
            "-i",
            "testsrc=duration=2:size=320x240:rate=10",
            "-f",
            "lavfi",
            "-i",
            "sine=frequency=440:duration=2",
            "-c:v",
            "libx264",
            "-pix_fmt",
            "yuv420p",
            "-c:a",
            "aac",
            "-shortest",
            "-y",
        ])
        .arg(path)
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}

/// Generate a 1 s silent-but-present sine audio-only file.
fn make_audio(path: &Path) -> bool {
    Command::new("ffmpeg")
        .args([
            "-v",
            "error",
            "-f",
            "lavfi",
            "-i",
            "sine=frequency=220:duration=1",
            "-y",
        ])
        .arg(path)
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}

#[test]
fn probe_reports_dimensions_fps_and_audio() {
    if !ffprobe_available() {
        eprintln!("skip: ffprobe not available");
        return;
    }
    let dir = tempfile::tempdir().unwrap();
    let av = dir.path().join("av.mp4");
    if !make_av(&av) {
        eprintln!("skip: could not generate test media");
        return;
    }

    let p = probe(&av).unwrap();
    assert!(p.has_video);
    assert!(p.has_audio);
    assert_eq!(p.width, Some(320));
    assert_eq!(p.height, Some(240));
    assert!(p.fps.unwrap() > 9.0 && p.fps.unwrap() < 11.0);
    assert!(p.duration_secs > 1.5 && p.duration_secs < 2.5);
}

#[test]
fn decode_frame_returns_rgba_of_expected_size() {
    if !ffmpeg_available() {
        eprintln!("skip: ffmpeg not available");
        return;
    }
    let dir = tempfile::tempdir().unwrap();
    let av = dir.path().join("av.mp4");
    if !make_av(&av) {
        return;
    }

    let req = FrameRequest {
        time_secs: 1.0,
        max_size: (0, 0),
        apply_rotation: true,
    };
    let (_actual, frame) = decode_frame_at(&av, &req).unwrap();
    assert_eq!(frame.width, 320);
    assert_eq!(frame.height, 240);
    assert_eq!(frame.rgba.len(), 320 * 240 * 4);
}

#[test]
fn decode_frame_scales_within_box() {
    if !ffmpeg_available() {
        return;
    }
    let dir = tempfile::tempdir().unwrap();
    let av = dir.path().join("av.mp4");
    if !make_av(&av) {
        return;
    }
    let req = FrameRequest {
        time_secs: 0.5,
        max_size: (120, 68),
        apply_rotation: true,
    };
    let (_t, frame) = decode_frame_at(&av, &req).unwrap();
    // 320x240 into 120x68 → height-limited (68), width 90.
    assert!(frame.width <= 120 && frame.height <= 68);
    assert_eq!(
        frame.rgba.len(),
        frame.width as usize * frame.height as usize * 4
    );
}

#[test]
fn extract_pcm_yields_16k_mono() {
    if !ffmpeg_available() {
        return;
    }
    let dir = tempfile::tempdir().unwrap();
    let av = dir.path().join("av.mp4");
    if !make_av(&av) {
        return;
    }
    let spec = PcmSpec {
        sample_rate: 16_000,
        channels: 1,
        format: PcmFormat::F32,
    };
    let pcm = extract_pcm(&av, &spec, None).unwrap();
    // ~2 s of 16 kHz mono ≈ 32000 samples (allow generous tolerance).
    assert!(pcm.samples_f32.len() > 24_000 && pcm.samples_f32.len() < 40_000);
    assert!((pcm.duration_secs() - 2.0).abs() < 0.5);
}

#[test]
fn extract_pcm_without_explicit_range_matches_full_track_decode() {
    if !ffmpeg_available() {
        return;
    }
    let dir = tempfile::tempdir().unwrap();
    let av = dir.path().join("aac-full-track.mp4");
    let ffmpeg = ffmpeg_path();
    let generated = Command::new(&ffmpeg)
        .args([
            "-v",
            "error",
            "-f",
            "lavfi",
            "-i",
            "color=c=0x336699:s=32x18:r=4",
            "-f",
            "lavfi",
            "-i",
            "sine=frequency=440:sample_rate=16000",
            "-t",
            "1",
            "-c:v",
            "mpeg4",
            "-c:a",
            "aac",
            "-y",
        ])
        .arg(&av)
        .status()
        .map(|status| status.success())
        .unwrap_or(false);
    if !generated {
        return;
    }

    let direct = Command::new(&ffmpeg)
        .args(["-v", "error", "-i"])
        .arg(&av)
        .args(["-vn", "-ac", "1", "-ar", "16000", "-f", "f32le", "-"])
        .output()
        .unwrap();
    assert!(direct.status.success(), "direct ffmpeg decode must succeed");
    assert_eq!(direct.stdout.len() % 4, 0, "f32 PCM byte count must align");

    let spec = PcmSpec {
        sample_rate: 16_000,
        channels: 1,
        format: PcmFormat::F32,
    };
    let pcm = extract_pcm(&av, &spec, None).unwrap();
    assert_eq!(
        pcm.samples_f32.len(),
        direct.stdout.len() / 4,
        "range=None must decode the full track, not an implicit [0,duration] window"
    );
}

#[test]
fn whole_track_pcm_decodes_a_vbr_mp3_past_its_estimated_duration() {
    if !ffmpeg_available() || !ffprobe_available() {
        eprintln!("skip: ffmpeg not available");
        return;
    }
    let dir = tempfile::tempdir().unwrap();
    let mp3 = dir.path().join("vbr-no-xing.mp3");
    // 20 s of noise then 100 s of silence as VBR MP3 without a Xing header:
    // the demuxer estimates the duration from the loud opening frames.
    let generated = Command::new(ffmpeg_path())
        .args(["-v", "error", "-y"])
        .args(["-f", "lavfi", "-i", "anoisesrc=d=20:r=48000"])
        .args(["-f", "lavfi", "-i", "anullsrc=r=48000:cl=mono:d=100"])
        .args(["-filter_complex", "[0][1]concat=n=2:v=0:a=1"])
        .args(["-c:a", "libmp3lame", "-q:a", "5", "-write_xing", "0"])
        .arg(&mp3)
        .status()
        .is_ok_and(|status| status.success());
    if !generated {
        eprintln!("skip: this ffmpeg cannot encode MP3");
        return;
    }
    let estimated = probe(&mp3).unwrap();
    assert!(
        estimated.duration_secs < 100.0,
        "fixture must be underestimated, got {}",
        estimated.duration_secs
    );

    let spec = PcmSpec {
        sample_rate: 16_000,
        channels: 1,
        format: PcmFormat::F32,
    };
    let pcm = extract_pcm(&mp3, &spec, None).expect("whole-track VBR MP3 decode");
    assert!(
        (pcm.duration_secs() - 120.0).abs() < 0.1,
        "decoded {} s",
        pcm.duration_secs()
    );
}

#[test]
fn whole_track_pcm_keeps_audio_that_outlasts_the_video() {
    if !ffmpeg_available() || !ffprobe_available() {
        eprintln!("skip: ffmpeg not available");
        return;
    }
    let dir = tempfile::tempdir().unwrap();
    let clip = dir.path().join("long-audio.mp4");
    let generated = Command::new(ffmpeg_path())
        .args(["-v", "error", "-y"])
        .args(["-f", "lavfi", "-i", "testsrc2=size=64x36:rate=30:d=2"])
        .args([
            "-f",
            "lavfi",
            "-i",
            "sine=frequency=440:sample_rate=48000:d=4",
        ])
        .args(["-c:v", "mpeg4", "-c:a", "aac"])
        .arg(&clip)
        .status()
        .unwrap();
    assert!(generated.success(), "generate long-audio fixture");
    let probed = probe(&clip).unwrap();
    assert!((probed.duration_secs - 2.0).abs() < 0.1, "{probed:?}");
    assert!(probed.audio_duration_secs.is_some_and(|audio| audio > 3.9));

    let spec = PcmSpec {
        sample_rate: 48_000,
        channels: 2,
        format: PcmFormat::F32,
    };
    let interleaved = opentake_media::decode_pcm_interleaved_cancellable(
        &clip,
        &spec,
        None,
        &opentake_media::MediaCancelToken::new(),
    )
    .expect("whole-track decode keeps the audio past the video");
    let seconds = interleaved.len() as f64 / 2.0 / 48_000.0;
    assert!((seconds - 4.0).abs() < 0.1, "decoded {seconds} s");
}

#[test]
fn extract_pcm_range_is_shorter() {
    if !ffmpeg_available() {
        return;
    }
    let dir = tempfile::tempdir().unwrap();
    let av = dir.path().join("av.mp4");
    if !make_av(&av) {
        return;
    }
    let spec = PcmSpec {
        sample_rate: 16_000,
        channels: 1,
        format: PcmFormat::F32,
    };
    // 0.5 s window ≈ 8000 samples.
    let pcm = extract_pcm(&av, &spec, Some((0.5, 1.0))).unwrap();
    let n = pcm.samples_f32.len();
    assert!(n > 4_000 && n < 12_000, "got {n} samples for a 0.5s window");
}

#[test]
fn extract_pcm_no_audio_track_errors() {
    if !ffmpeg_available() {
        return;
    }
    let dir = tempfile::tempdir().unwrap();
    let video_only = dir.path().join("v.mp4");
    let ok = Command::new("ffmpeg")
        .args([
            "-v",
            "error",
            "-f",
            "lavfi",
            "-i",
            "testsrc=duration=1:size=64x64:rate=5",
            "-c:v",
            "libx264",
            "-pix_fmt",
            "yuv420p",
            "-y",
        ])
        .arg(&video_only)
        .status()
        .map(|s| s.success())
        .unwrap_or(false);
    if !ok {
        return;
    }
    let spec = PcmSpec {
        sample_rate: 16_000,
        channels: 1,
        format: PcmFormat::F32,
    };
    let err = extract_pcm(&video_only, &spec, None);
    assert!(
        err.is_err(),
        "expected NoTrack error for video without audio"
    );
}

#[test]
fn extract_pcm_empty_stdout_errors_not_silent_buffer() {
    // Regression for the "ffmpeg exits 0 but emits no PCM" case: a range window
    // entirely past the media end seeks past EOF, so ffmpeg succeeds yet writes
    // zero bytes. extract_pcm must surface NoTrack rather than return an empty
    // buffer — an empty buffer downstream poisons the waveform cache with an
    // all-1.0 flat band.
    if !ffmpeg_available() {
        return;
    }
    let dir = tempfile::tempdir().unwrap();
    let av = dir.path().join("av.mp4");
    if !make_av(&av) {
        return;
    }
    let spec = PcmSpec {
        sample_rate: 16_000,
        channels: 1,
        format: PcmFormat::F32,
    };
    // The clip is ~2 s long; ask for [5.0, 6.0) → past EOF → empty stdout.
    let res = extract_pcm(&av, &spec, Some((5.0, 6.0)));
    assert!(
        res.is_err(),
        "expected an error for an empty PCM window, not a silent buffer"
    );
}

#[test]
fn waveform_has_expected_bucket_count() {
    if !ffmpeg_available() {
        return;
    }
    let dir = tempfile::tempdir().unwrap();
    let audio = dir.path().join("a.wav");
    if !make_audio(&audio) {
        return;
    }
    // 1 s → max(4000, 150) = 4000 buckets, values in [0,1].
    let wf = waveform(&audio, 1.0).unwrap();
    assert_eq!(wf.len(), 4000);
    assert!(wf.iter().all(|&v| (0.0..=1.0).contains(&v)));
    // A 220 Hz tone is loud → at least some buckets well below 1 (not silence).
    let min = wf.iter().copied().fold(f32::INFINITY, f32::min);
    assert!(min < 0.5, "expected loud buckets, min={min}");
}

#[test]
fn waveform_decodes_audio_from_mp4_video_container() {
    // Regression guard: the waveform path must decode the audio track that lives
    // INSIDE a video container (the common case — a clip's `media_ref` points at
    // the video file, and its linked audio reuses that ref). The earlier
    // pure-Rust decoder failed on many such containers while ffmpeg probe/thumb
    // succeeded, so the audio clip rendered as a flat band with no waveform.
    if !ffmpeg_available() {
        return;
    }
    let dir = tempfile::tempdir().unwrap();
    let av = dir.path().join("av.mp4"); // H.264 video + AAC audio
    if !make_av(&av) {
        return;
    }
    // 2 s → max(4000, 2*150) = 4000 buckets, values in [0,1].
    let wf = waveform(&av, 2.0).unwrap();
    assert_eq!(wf.len(), 4000);
    assert!(wf.iter().all(|&v| (0.0..=1.0).contains(&v)));
    // The 440 Hz sine track is loud → some buckets well below 1 (not silence).
    let min = wf.iter().copied().fold(f32::INFINITY, f32::min);
    assert!(
        min < 0.5,
        "expected loud buckets from the AAC track, min={min}"
    );
}

#[test]
fn video_thumbnails_generates_and_caches() {
    if !ffmpeg_available() {
        return;
    }
    let dir = tempfile::tempdir().unwrap();
    let cache = tempfile::tempdir().unwrap();
    let av = dir.path().join("av.mp4");
    if !make_av(&av) {
        return;
    }

    // 2 s clip (<10) → interval 1 → times 0,1 → up to 2 thumbnails.
    let thumbs = video_thumbnails(cache.path(), &av, 2.0, None).unwrap();
    assert!(!thumbs.is_empty());
    assert!(thumbs.len() <= 2);
    // Tiles scaled within the 120x68 box.
    assert!(thumbs[0].image.width <= 120 && thumbs[0].image.height <= 68);

    // Second call hits the sprite cache and returns the same count.
    let again = video_thumbnails(cache.path(), &av, 2.0, None).unwrap();
    assert_eq!(again.len(), thumbs.len());
}

#[test]
fn encode_roundtrip_produces_playable_video() {
    if !ffmpeg_available() || !ffprobe_available() {
        return;
    }
    let dir = tempfile::tempdir().unwrap();
    let out = dir.path().join("out.mp4");

    let preset = ExportPreset::new(VideoCodec::H264, ExportResolution::P720);
    let (w, h) = (64u32, 64u32);
    let mut enc = VideoEncoder::new(&out, w, h, 10, &preset).unwrap();
    // Push 10 frames of solid color.
    for i in 0..10u8 {
        let mut rgba = vec![0u8; (w * h * 4) as usize];
        for px in rgba.as_chunks_mut::<4>().0.iter_mut() {
            px[0] = i * 20;
            px[1] = 100;
            px[2] = 200;
            px[3] = 255;
        }
        enc.push_frame(&opentake_media::RgbaFrame::new(w, h, rgba))
            .unwrap();
    }
    enc.finish().unwrap();

    // The output decodes back to a 64x64 video of ~1 s.
    let p = probe(&out).unwrap();
    assert!(p.has_video);
    assert_eq!(p.width, Some(64));
    assert_eq!(p.height, Some(64));
    assert!(p.duration_secs > 0.5);

    // Ensure the encode module's preset arg builder agrees with reality.
    let _ = encode::preset::even_dimension(63); // referenced for coverage
}

fn encode_codec_roundtrip(codec: VideoCodec, extension: &str, expected_codec: &str) {
    if !ffmpeg_available() || !ffprobe_available() {
        return;
    }
    let dir = tempfile::tempdir().unwrap();
    let out = dir.path().join(format!("roundtrip.{extension}"));
    let preset = ExportPreset::new(codec, ExportResolution::P720);
    let (width, height) = (64_u32, 64_u32);
    let mut encoder = VideoEncoder::new(&out, width, height, 10, &preset).unwrap();
    for index in 0..6_u8 {
        let mut rgba = vec![0_u8; (width * height * 4) as usize];
        for pixel in rgba.as_chunks_mut::<4>().0.iter_mut() {
            pixel.copy_from_slice(&[index.saturating_mul(30), 80, 180, 255]);
        }
        encoder
            .push_frame(&opentake_media::RgbaFrame::new(width, height, rgba))
            .unwrap();
    }
    encoder.finish().unwrap();

    let codec_name = Command::new("ffprobe")
        .args([
            "-v",
            "error",
            "-select_streams",
            "v:0",
            "-show_entries",
            "stream=codec_name",
            "-of",
            "default=noprint_wrappers=1:nokey=1",
        ])
        .arg(&out)
        .output()
        .unwrap();
    assert!(codec_name.status.success());
    assert_eq!(
        String::from_utf8_lossy(&codec_name.stdout).trim(),
        expected_codec
    );
    let format_name = Command::new("ffprobe")
        .args([
            "-v",
            "error",
            "-show_entries",
            "format=format_name",
            "-of",
            "default=noprint_wrappers=1:nokey=1",
        ])
        .arg(&out)
        .output()
        .unwrap();
    assert!(format_name.status.success());
    assert!(
        String::from_utf8_lossy(&format_name.stdout)
            .split(',')
            .any(|name| name.trim() == extension),
        "ffprobe format must include {extension}"
    );
    let media = probe(&out).unwrap();
    assert!(media.has_video);
    assert_eq!(media.width, Some(width));
    assert_eq!(media.height, Some(height));
}

#[test]
fn encode_h265_roundtrip_produces_hevc_mp4() {
    encode_codec_roundtrip(VideoCodec::H265, "mp4", "hevc");
}

#[test]
fn encode_prores_roundtrip_produces_prores_mov() {
    encode_codec_roundtrip(VideoCodec::ProRes422, "mov", "prores");
}

#[test]
fn prores_4444_roundtrip_preserves_alpha_plane() {
    if !ffmpeg_available() || !ffprobe_available() {
        eprintln!("SKIP: ffmpeg/ffprobe unavailable");
        return;
    }
    let root = tempfile::tempdir().unwrap();
    let output = root.path().join("alpha.mov");
    let preset = ExportPreset::new(VideoCodec::ProRes4444, ExportResolution::P720);
    let mut encoder = VideoEncoder::new(&output, 2, 2, 1, &preset).unwrap();
    encoder
        .push_frame(&RgbaFrame {
            width: 2,
            height: 2,
            rgba: vec![
                255, 0, 0, 0, 0, 255, 0, 85, 0, 0, 255, 170, 255, 255, 255, 255,
            ],
        })
        .unwrap();
    encoder.finish().unwrap();
    let decoded = decode_frame_at(
        &output,
        &FrameRequest {
            max_size: (2, 2),
            ..FrameRequest::default()
        },
    )
    .unwrap()
    .1;
    let alpha = decoded
        .rgba
        .as_chunks::<4>()
        .0
        .iter()
        .map(|pixel| pixel[3])
        .collect::<Vec<_>>();
    for (actual, expected) in alpha.iter().zip([0_u8, 85, 170, 255]) {
        assert!(actual.abs_diff(expected) <= 3, "{alpha:?}");
    }
}

#[test]
#[ignore = "requires OPENTAKE_MAIN10_FIXTURE pointing at a real HEVC Main10 clip"]
fn continuous_decode_scales_real_main10_frames_without_corruption() {
    let path = std::env::var_os("OPENTAKE_MAIN10_FIXTURE")
        .map(std::path::PathBuf::from)
        .expect("set OPENTAKE_MAIN10_FIXTURE");
    let mut request = VideoStreamRequest::new(path, 30);
    request.start_frame = 1_572;
    request.end_frame = Some(request.start_frame + 90);
    request.max_size = (1_920, 1_080);

    let stream = spawn_video_stream(request).unwrap();
    for _ in 0..90 {
        let decoded = stream
            .receiver()
            .recv_timeout(std::time::Duration::from_secs(10))
            .expect("continuous decoder frame")
            .expect("continuous decoder success");

        assert_eq!((decoded.frame.width, decoded.frame.height), (1_920, 1_080));
        assert_eq!(decoded.frame.rgba.len(), 1_920 * 1_080 * 4);
        let neon_green = decoded
            .frame
            .rgba
            .as_chunks::<4>()
            .0
            .iter()
            .filter(|pixel| pixel[0] < 32 && pixel[1] > 224 && pixel[2] < 32)
            .count();
        assert!(
            neon_green < decoded.frame.pixel_count() / 100,
            "frame {} contains {neon_green} neon-green pixels",
            decoded.source_frame
        );
    }
}

/// Lossless frame-numbered clip: columns `2b..2b+1` are white when bit `b` of
/// the source frame number is set, so the number survives whatever YUV range
/// conversion the local ffmpeg applies. `vf` retimes the frames.
fn make_numbered(path: &Path, fps: &str, frames: u32, vf: Option<&str>) -> bool {
    let mut command = Command::new("ffmpeg");
    command.args([
        "-v",
        "error",
        "-f",
        "lavfi",
        "-i",
        &format!(
            "color=black:s=16x16:r={fps},format=gray,geq=lum='if(mod(floor(N/pow(2,floor(X/2))),2),235,16)'"
        ),
        "-frames:v",
        &frames.to_string(),
    ]);
    if let Some(vf) = vf {
        command.args(["-vf", vf, "-fps_mode", "vfr"]);
    }
    command
        .args([
            "-c:v", "libx264", "-crf", "0", "-g", "15", "-pix_fmt", "yuv420p", "-y",
        ])
        .arg(path)
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}

fn source_index(frame: &RgbaFrame) -> i64 {
    let row = (frame.height / 2 * frame.width) as usize * 4;
    (0..8)
        .filter(|bit| frame.rgba[row + (bit * 2 + 1) * 4] > 128)
        .map(|bit| 1 << bit)
        .sum()
}

fn frame_at(path: &Path, time_secs: f64) -> (f64, i64) {
    let (actual, frame) = decode_frame_at(
        path,
        &FrameRequest {
            time_secs,
            ..FrameRequest::default()
        },
    )
    .unwrap();
    (actual, source_index(&frame))
}

/// `(timeline frame, source frame)` for every frame the stream emits.
fn streamed(path: &Path, fps: i32, start: i64, end: i64) -> Vec<(i64, i64)> {
    let mut request = VideoStreamRequest::new(path, fps);
    request.start_frame = start;
    request.end_frame = Some(end);
    let stream = spawn_video_stream(request).unwrap();
    let mut out = Vec::new();
    while let Ok(result) = stream
        .receiver()
        .recv_timeout(std::time::Duration::from_secs(10))
    {
        let decoded = result.expect("continuous decode frame");
        out.push((decoded.source_frame, source_index(&decoded.frame)));
    }
    out
}

#[test]
fn decode_frame_returns_the_displayed_frame_and_its_real_pts() {
    if !ffmpeg_available() || !ffprobe_available() {
        eprintln!("skip: ffmpeg not available");
        return;
    }
    let dir = tempfile::tempdir().unwrap();
    let clip = dir.path().join("numbered30.mp4");
    if !make_numbered(&clip, "30", 150, None) {
        eprintln!("skip: could not generate test media");
        return;
    }

    let (actual, index) = frame_at(&clip, 3.0);
    assert_eq!(index, 90);
    assert!((actual - 3.0).abs() < 1e-5, "{actual}");
    // Between frames the one still on screen is returned with its own pts.
    let (actual, index) = frame_at(&clip, 3.02);
    assert_eq!(index, 90);
    assert!((actual - 3.0).abs() < 1e-5, "{actual}");

    // Thumbnail-style batch: t=0 and t=1 are different frames; a request that
    // lands on an already-emitted frame is de-duplicated by its real pts.
    let batch = decode_frames_at(&clip, &[0.0, 1.0, 1.01], &FrameRequest::default())
        .into_iter()
        .map(|result| {
            let (actual, frame) = result.unwrap();
            (actual, source_index(&frame))
        })
        .collect::<Vec<_>>();
    assert_eq!(batch.len(), 2, "{batch:?}");
    assert_eq!((batch[0].1, batch[1].1), (0, 30));
    assert!((batch[1].0 - 1.0).abs() < 1e-5);

    // The retained-handle path decodes from the open file instead of the
    // pathname; it must select the same frame.
    let file = std::fs::File::open(&clip).unwrap();
    let (actual, frame) = decode_frame_file_at_cancellable(
        &file,
        &FrameRequest {
            time_secs: 3.02,
            ..FrameRequest::default()
        },
        &opentake_media::MediaCancelToken::new(),
    )
    .unwrap();
    assert_eq!(source_index(&frame), 90);
    assert!((actual - 3.0).abs() < 1e-5, "{actual}");
}

/// `(actual pts in µs, source frame)` per emitted frame of a batch decode.
fn batched(path: &Path, times: &[f64]) -> Vec<(i64, i64)> {
    decode_frames_at(path, times, &FrameRequest::default())
        .into_iter()
        .map(|result| {
            let (actual, frame) = result.expect("batched frame");
            ((actual * 1e6).round() as i64, source_index(&frame))
        })
        .collect()
}

/// The same selection made one seek-decode at a time, with the batch API's
/// `t > lastTime` de-duplication.
fn one_by_one(path: &Path, times: &[f64]) -> Vec<(i64, i64)> {
    let mut last = f64::NEG_INFINITY;
    let mut out = Vec::new();
    for &time in times {
        let (actual, index) = frame_at(path, time);
        if actual > last {
            last = actual;
            out.push(((actual * 1e6).round() as i64, index));
        }
    }
    out
}

#[test]
fn batched_forward_decode_matches_single_frame_decodes() {
    if !ffmpeg_available() || !ffprobe_available() {
        eprintln!("skip: ffmpeg not available");
        return;
    }
    let dir = tempfile::tempdir().unwrap();
    let cfr = dir.path().join("numbered30.mp4");
    let vfr = dir.path().join("vfr.mp4");
    if !make_numbered(&cfr, "30", 150, None)
        || !make_numbered(&vfr, "30", 60, Some("setpts='if(gte(N,30),PTS+1/TB,PTS)'"))
    {
        eprintln!("skip: could not generate test media");
        return;
    }

    let half_seconds = (0..10).map(|i| i as f64 * 0.5).collect::<Vec<_>>();
    for times in [
        vec![0.0, 1.0, 2.0, 3.0, 4.0],
        half_seconds,
        // A grid subset whose last target repeats the frame at 1.0 s.
        vec![0.0, 1.0, 1.01, 2.5, 4.9],
    ] {
        let expected = one_by_one(&cfr, &times);
        assert_eq!(batched(&cfr, &times), expected, "targets {times:?}");
    }
    assert_eq!(
        batched(&cfr, &[0.0, 1.0, 2.0])
            .into_iter()
            .map(|(_, index)| index)
            .collect::<Vec<_>>(),
        vec![0, 30, 60]
    );

    // Across a one-second VFR gap the frame before the gap stays on screen.
    let times = [0.5, 1.0, 1.5, 2.0, 2.5];
    let expected = one_by_one(&vfr, &times);
    assert_eq!(
        expected.iter().map(|(_, index)| *index).collect::<Vec<_>>(),
        vec![15, 29, 30, 45]
    );
    assert_eq!(batched(&vfr, &times), expected);
}

#[test]
fn vfr_gap_single_and_streamed_frames_hold_the_last_displayed_frame() {
    if !ffmpeg_available() || !ffprobe_available() {
        eprintln!("skip: ffmpeg not available");
        return;
    }
    let dir = tempfile::tempdir().unwrap();
    let clip = dir.path().join("vfr.mp4");
    // Source frames 0-29 at 0-0.967s, frame 30 onward shifted to 2.0s.
    if !make_numbered(&clip, "30", 60, Some("setpts='if(gte(N,30),PTS+1/TB,PTS)'")) {
        eprintln!("skip: could not generate test media");
        return;
    }

    let (actual, index) = frame_at(&clip, 1.2);
    assert_eq!(index, 29);
    assert!((actual - 29.0 / 30.0).abs() < 1e-5, "{actual}");

    let frames = streamed(&clip, 30, 36, 64);
    let expected = (36..64)
        .map(|timeline| (timeline, if timeline < 60 { 29 } else { timeline - 30 }))
        .collect::<Vec<_>>();
    assert_eq!(frames, expected);
}

#[test]
fn mismatched_fps_single_and_streamed_frames_follow_floor_rule() {
    if !ffmpeg_available() || !ffprobe_available() {
        eprintln!("skip: ffmpeg not available");
        return;
    }
    let dir = tempfile::tempdir().unwrap();
    let clip = dir.path().join("numbered24.mp4");
    if !make_numbered(&clip, "24", 60, None) {
        eprintln!("skip: could not generate test media");
        return;
    }
    let expected = |timeline: i64| timeline * 24 / 30;

    let from_start = streamed(&clip, 30, 0, 60);
    assert_eq!(
        from_start,
        (0..60).map(|f| (f, expected(f))).collect::<Vec<_>>()
    );
    // Starting mid-clip keeps the same grid instead of re-anchoring at the
    // first decoded frame.
    let mid = streamed(&clip, 30, 37, 60);
    assert_eq!(mid, (37..60).map(|f| (f, expected(f))).collect::<Vec<_>>());
    for timeline in 0..60 {
        let (_, index) = frame_at(&clip, timeline as f64 / 30.0);
        assert_eq!(index, expected(timeline), "timeline frame {timeline}");
    }
}

#[test]
fn same_fps_single_and_streamed_frames_are_identity() {
    if !ffmpeg_available() || !ffprobe_available() {
        eprintln!("skip: ffmpeg not available");
        return;
    }
    let dir = tempfile::tempdir().unwrap();
    let clip = dir.path().join("numbered30.mp4");
    if !make_numbered(&clip, "30", 90, None) {
        eprintln!("skip: could not generate test media");
        return;
    }

    for start in [0, 1, 44] {
        let frames = streamed(&clip, 30, start, 90);
        assert_eq!(frames, (start..90).map(|f| (f, f)).collect::<Vec<_>>());
    }
    for timeline in [0, 1, 14, 15, 16, 59, 89] {
        let (actual, index) = frame_at(&clip, timeline as f64 / 30.0);
        assert_eq!(index, timeline);
        assert!((actual - timeline as f64 / 30.0).abs() < 1e-5);
    }
}

#[test]
fn ntsc_source_on_integer_timeline_matches_between_single_and_streamed_frames() {
    if !ffmpeg_available() || !ffprobe_available() {
        eprintln!("skip: ffmpeg not available");
        return;
    }
    let dir = tempfile::tempdir().unwrap();
    let clip = dir.path().join("numbered2997.mp4");
    if !make_numbered(&clip, "30000/1001", 250, None) {
        eprintln!("skip: could not generate test media");
        return;
    }
    // Timeline frame F shows the last 29.97 fps source frame at or before
    // F / 30 s; the drift accumulates instead of rounding to the nearest frame.
    let expected = |timeline: i64| timeline * 1000 / 1001;
    let streamed_frames = streamed(&clip, 30, 0, 248);
    assert_eq!(
        streamed_frames,
        (0..248).map(|f| (f, expected(f))).collect::<Vec<_>>()
    );
    // Paused preview and export resolve Nearest through single-frame decode.
    for timeline in [0, 1, 2, 29, 30, 31, 120, 247] {
        let (_, index) = frame_at(&clip, timeline as f64 / 30.0);
        assert_eq!(index, expected(timeline), "timeline frame {timeline}");
    }
}

/// Flip `count` bytes inside the `mdat` payload with a fixed-seed xorshift so
/// the damage is deterministic and never touches the container index.
fn corrupt_mdat(path: &Path, count: usize) {
    let mut bytes = std::fs::read(path).unwrap();
    let tag = bytes
        .windows(4)
        .position(|window| window == b"mdat")
        .expect("mp4 has an mdat box");
    let size = u32::from_be_bytes(bytes[tag - 4..tag].try_into().unwrap()) as usize;
    let (start, end) = (tag + 64, tag - 4 + size - 64);
    let mut state = 0x2545_f491_4f6c_dd1d_u64;
    for _ in 0..count {
        state ^= state << 13;
        state ^= state >> 7;
        state ^= state << 17;
        let offset = start + (state as usize) % (end - start);
        bytes[offset] ^= 0xff;
    }
    std::fs::write(path, bytes).unwrap();
}

fn stream_results(path: &Path) -> (usize, Vec<String>) {
    let stream = spawn_video_stream(VideoStreamRequest::new(path, 30)).unwrap();
    let (mut frames, mut errors) = (0, Vec::new());
    while let Ok(result) = stream
        .receiver()
        .recv_timeout(std::time::Duration::from_secs(20))
    {
        match result {
            Ok(_) => frames += 1,
            Err(error) => errors.push(error.to_string()),
        }
    }
    (frames, errors)
}

#[test]
fn continuous_decode_conceals_recoverable_bitstream_errors() {
    if !ffmpeg_available() || !ffprobe_available() {
        eprintln!("skip: ffmpeg not available");
        return;
    }
    let dir = tempfile::tempdir().unwrap();
    let clip = dir.path().join("damaged.mp4");
    let generated = Command::new("ffmpeg")
        .args([
            "-v",
            "error",
            "-f",
            "lavfi",
            "-i",
            "testsrc=duration=20:size=160x120:rate=30",
            "-c:v",
            "libx264",
            "-g",
            "60",
            "-pix_fmt",
            "yuv420p",
            "-y",
        ])
        .arg(&clip)
        .status()
        .map(|status| status.success())
        .unwrap_or(false);
    if !generated {
        eprintln!("skip: could not generate test media");
        return;
    }
    corrupt_mdat(&clip, 40);
    let check = Command::new(ffmpeg_path())
        .args(["-v", "error", "-i"])
        .arg(&clip)
        .args(["-f", "null", "-"])
        .output()
        .unwrap();
    assert!(check.status.success(), "ffmpeg itself decodes the damage");
    assert!(
        String::from_utf8_lossy(&check.stderr).contains("error"),
        "fixture must make the decoder log recoverable errors"
    );

    let (frames, errors) = stream_results(&clip);
    assert!(errors.is_empty(), "{errors:?}");
    assert_eq!(frames, 600);
}

#[test]
fn continuous_decode_reports_real_failures_with_the_log_tail() {
    if !ffmpeg_available() || !ffprobe_available() {
        eprintln!("skip: ffmpeg not available");
        return;
    }
    let dir = tempfile::tempdir().unwrap();
    let garbage = dir.path().join("garbage.mp4");
    std::fs::write(&garbage, vec![0x5a_u8; 4096]).unwrap();

    for path in [dir.path().join("missing.mp4"), garbage] {
        let (frames, errors) = stream_results(&path);
        assert_eq!(frames, 0);
        assert_eq!(errors.len(), 1, "{errors:?}");
        assert!(errors[0].contains("ffmpeg exited with"), "{}", errors[0]);
        assert!(errors[0].contains("Error opening input"), "{}", errors[0]);
    }
}

/// A file name that is not valid UTF-8 reaches ffmpeg byte for byte: the
/// encoder writes it, and frame, stream and PCM decoding all read it back.
/// A lossy conversion would replace `\xff` with U+FFFD and open another path.
#[cfg(target_os = "linux")]
#[test]
fn non_utf8_file_names_encode_and_decode() {
    use std::ffi::OsStr;
    use std::os::unix::ffi::OsStrExt;

    use opentake_media::{decode_pcm_interleaved, MediaCancelToken, PcmBuffer, PcmStream};

    if !ffmpeg_available() || !ffprobe_available() {
        return;
    }
    let dir = tempfile::tempdir().unwrap();
    let out = dir.path().join(OsStr::from_bytes(b"clip-\xff.mp4"));
    assert!(out.to_str().is_none(), "fixture name must not be UTF-8");

    let preset = ExportPreset::new(VideoCodec::H264, ExportResolution::P720);
    let (w, h) = (64_u32, 48_u32);
    let mut encoder = VideoEncoder::new(&out, w, h, 10, &preset).unwrap();
    for index in 0..10_u8 {
        let rgba = [index * 20, 100, 200, 255].repeat((w * h) as usize);
        encoder.push_frame(&RgbaFrame::new(w, h, rgba)).unwrap();
    }
    let mono = PcmSpec {
        sample_rate: 48_000,
        channels: 1,
        format: PcmFormat::F32,
    };
    encoder
        .push_audio(PcmBuffer {
            spec: mono,
            samples_f32: (0..48_000)
                .map(|index| (index as f32 * 0.0575).sin() * 0.5)
                .collect(),
        })
        .unwrap();
    encoder.finish().unwrap();
    assert!(out.is_file());

    let probed = probe(&out).unwrap();
    assert!(probed.has_video && probed.has_audio);

    let (_, frame) = decode_frame_at(&out, &FrameRequest::default()).unwrap();
    assert_eq!((frame.width, frame.height), (w, h));

    let stream = spawn_video_stream(VideoStreamRequest::new(out.clone(), 10)).unwrap();
    let decoded = stream
        .receiver()
        .recv_timeout(std::time::Duration::from_secs(10))
        .expect("stream frame")
        .expect("stream decode");
    assert_eq!((decoded.frame.width, decoded.frame.height), (w, h));
    drop(stream);

    let pcm = extract_pcm(&out, &mono, None).unwrap();
    assert!(pcm.samples_f32.len() > 40_000);
    let stereo = PcmSpec {
        sample_rate: 48_000,
        channels: 2,
        format: PcmFormat::F32,
    };
    let interleaved = decode_pcm_interleaved(&out, &stereo, Some((0.0, 0.5))).unwrap();
    assert!(interleaved.len() > 40_000);
    let mut pcm_stream =
        PcmStream::open(&out, &stereo, (0.0, 0.5), &MediaCancelToken::new()).unwrap();
    let mut streamed = Vec::new();
    assert!(pcm_stream.read(1_024, &mut streamed).unwrap() > 0);
}
